### ISSUE TITLE
API being 2 minutes late on results

### ISSUE THREAD

**Issue by MrRadium** [maanavshah/stock-market-india#19]
The project is very good but currently, I'm having an issue with the API from the NSE branch (I haven't tried the BSE branch still). It looks like that the results shown by the API are 2 minutes late. For example, if I do an API call at 15:00 it shows the last updated time to be 14:58. The market closes and opens 2 minutes delay from the actual time.

I just want to know if that is a problem with the API or it is just a mistake by me, if yes then is there a way I could fix it?

**Comment by Gidde-Abhishek** [comment]
I feel the delay is introduced by the NSE website because they sell real-time data and if they start showcasing real-time data freely it will hamper their business, though I personally feel this data should be provided free of cost.
A possible solution in my mind is to get data from a website that provides real-time data openly without a subscription, and none do that currently.
